# Generated by Django 5.2.5 on 2025-10-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0002_payment_coupons_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='order_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userpanel.ordersummary'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Return', 'Return')], default='Pending', max_length=50),
        ),
    ]
