# Generated by Django 5.2.5 on 2025-10-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0003_orderplaced_order_summary_alter_orderplaced_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='order_summary',
        ),
    ]
