# Generated by Django 5.2.5 on 2025-10-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0010_orderplaced_coupons_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='coupons_applied',
        ),
    ]
