# Generated by Django 5.2.5 on 2025-10-06 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0011_remove_orderplaced_coupons_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='coupons_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userpanel.coupon'),
        ),
    ]
