# Generated by Django 5.2.5 on 2025-10-06 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0012_orderplaced_coupons_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
