# Generated by Django 5.2.5 on 2025-10-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0016_orderplaced_city_orderplaced_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='coupons_applied',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
