# Generated by Django 5.2.5 on 2025-10-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0017_alter_payment_coupons_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='coupons_applied',
            new_name='discount_applied',
        ),
        migrations.AddField(
            model_name='payment',
            name='tax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
