# Generated by Django 5.2.5 on 2025-10-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0018_rename_coupons_applied_payment_discount_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='discount_applied',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tax',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
