# Generated by Django 5.2.5 on 2025-10-11 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0019_alter_payment_discount_applied_alter_payment_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='product_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='product_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='product_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userpanel.product'),
        ),
    ]
