# Generated by Django 5.2.5 on 2025-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0020_orderplaced_product_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='product_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
