# Generated by Django 5.2.5 on 2025-11-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0022_alter_product_product_image_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wallet_deduction',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
